accounts/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetDoneView,
    PasswordChangeDoneView,
    PasswordResetCompleteView
)

from .views import (
    UserPasswordChangeView,
    UserPasswordResetView,
    UserPasswordResetConfirmView,
    UserPasswordResetDoneView
)

urlpatterns = [
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('profile:login')), name='logout'),
    url(r'^password_change/$',
        UserPasswordChangeView.as_view(),
        name='password_change'),

    url(r'^password_change/done/$',
        UserPasswordResetDoneView.as_view(
            template_name='accounts/password_change_done.html',
        ),
        name='password_change_done'),

    url(r'^password_reset/$',
        UserPasswordResetView.as_view(),
        name='password_reset'),

    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),

    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

]

aproximeaty/urls.py
# NOTICE OF LICENSE
# This file is licenced under the Software License Agreement.
# With the purchase or the installation of the software in your application
# you accept the licence agreement.
#
# You must not modify, adapt or create derivative works of this source code
#
# @author: EL AKIOUI Zouhaire
# @copyright 2018
# @license   licence.txt


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.conf import settings
from aproximeaty import views as common_view


urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^item/', include('items.urls', namespace='item')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
]

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = common_view.handler404
handler500 = common_view.handler500

home/urls.py
from django.conf.urls import url
from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
]

accounts/models.py
from enum import Enum
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser, Group
from .managers import AproxUserManager


def upload_location(instance, filename):
    return "account/%s/%s" %(instance.slug, filename)


class AproxUser(AbstractUser):
    slug = models.SlugField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    address = models.CharField(_('Address'), max_length=120, blank=False, null=False, default='')
    zip_code = models.CharField(_('Zip code'), max_length=120, blank=False, null=False)
    city = models.CharField(_('City'), max_length=40, blank=False, null=False, default='')
    country = models.CharField(_('Country'), max_length=40, blank=False, null=False, default='')
    is_email_checked = models.BooleanField(
        _('Email checked'),
        default=False,
        help_text=_(
            'Designates whether this user checked his email. '
        ),
    )
    activate_key = models.CharField(max_length=120, blank=True, null=True, default='')
    image = models.ImageField(
        upload_to=upload_location,
        default='default.png',
        blank=True,
        null=True
    )
    phone_number = models.CharField(_('Phone number'), max_length=15, blank=False, null=False, default='')
    profile = models.CharField(null=False, max_length=8, default='Customer')


    manager = AproxUserManager


    def get_full_name(self):

        return self.email

    def get_short_name(self):
        return self.email

    def __str__(self):
        return self.email

    def verifyEmail(self):
        return self

    def get_profile(self):
        return self.profile

profiles/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Partner, Customer


class PartnerEditForm(forms.ModelForm):

    class Meta:
        model = Partner
        fields = '__all__'


class CustomerEditForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'gender',
            'civil_status',
            'address',
            'zip_code',
            'city',
            'country',
            'phone_number'
        ]


class PartnerRegisterForm(forms.ModelForm):

    class Meta:
        model = Partner
        fields = [
            'first_name',
            'last_name',
            'email',
            'password',
            'profile'
        ]

    def save(self, commit=True):
        partner = super(PartnerRegisterForm, self).save(commit=False)
        partner.username = self.cleaned_data.get('email')
        partner.save()
        return partner


class CustomerRegisterForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = [
            'first_name',
            'last_name',
            'email',
            'password',
            'profile'
        ]

    def save(self, commit=True):
        customer = super(CustomerRegisterForm, self).save(commit=False)
        customer.username = self.cleaned_data.get('email')
        customer.save()
        return customer


class ProfileRegisterForm(forms.Form):
    first_name = forms.CharField(max_length=20, min_length=2)
    last_name = forms.CharField(max_length=20, min_length=2)
    email = forms.EmailField()
    password = forms.CharField(max_length=16, min_length=8)
    profile = forms.CharField(max_length=8, required=True)

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if not first_name:
            raise forms.ValidationError(_('Your firstName is required'))
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if not last_name:
            raise forms.ValidationError(_('Your lastName is required'))
        return last_name

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if not email:
            raise forms.ValidationError(_('Your email address is required'))

        return email

    def clean_password(self):
        password = self.cleaned_data.get('password')

        if not password:
            raise forms.ValidationError(_('Please, enter your password'))

        if len(password) < 8:
            raise forms.ValidationError(_('Your password is small, minimum 8 characters'))

        if len(password) > 16:
            raise forms.ValidationError(_('Your password is long, max 16 characters'))

        return password


class ProfileLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(max_length=16, min_length=8, required=True)

accounts/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView
)


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    login_url = reverse_lazy('profile:register')

    @property
    def success_url(self):
        return reverse_lazy('profile:login')


class UserPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    email_template_name = 'accounts/password_reset_email.html'
    html_email_template_name = 'accounts/password_reset_email.html'

    def get_success_url(self):
        return reverse_lazy('account:password_reset_done')


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'

    def get_success_url(self):
        return reverse_lazy('account:password_reset_complete')


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'account/password_reset_done.html'

    def get_success_url(self):
        return reverse_lazy('profile:login')

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}


{% block content %}

    <p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

    <p><a href="{% url 'login' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block bodyclass %}{{ block.super }} login{% endblock %}
{% block content %}


  {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
      <p class="errornote">
          {{ error }}
      </p>
    {% endfor %}
  {% endif %}

  <div id="content-main">


    <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
      <div class="form-row">
        {{ form.username.errors }}
        {{ form.username.label_tag }} {{ form.username }}

      </div>
      <div class="form-row">
        {{ form.password.errors }}
        {{ form.password.label_tag }} {{ form.password }}
        <input type="hidden" name="next" value="{{ next }}" />
      </div>
      {% if password_reset_url %}
        <div class="password-reset-link">
          <a href="{% url 'account:password_reset' %}"> Mot de passe oublier</a>
        </div>
      {% endif %}
      <div class="submit-row">
        <input type="submit" value="Login" />
      </div>
    </form>

  </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'dash-base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock %}
{% block content_title %}
    <h1>{{ title }}</h1>
{% endblock %}
{% block content %}
<div class="wrapper">
        <!-- Sidebar -->
        {% include 'dashboard/snippets/sidebar-menu.html' %}
         <!-- Page Content -->
         <div id="content">
                <!-- Top menu -->
                {% include 'dashboard/snippets/top-menu.html' %}
                <p>{% trans 'Your password was changed.' %}</p>
        </div>
</div>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'dash-base.html' %}
{% load i18n static %}
{% block custom_css %}
    <link rel="stylesheet" href= "{% static 'accounts/css/accounts_change_password.css' %}" >
{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<div class="wrapper">
        <!-- Sidebar -->
        {% include 'dashboard/snippets/sidebar-menu.html' %}
         <!-- Page Content -->
         <div id="content">
                <!-- Top menu -->
                {% include 'dashboard/snippets/top-menu.html' %}
                <div class="container">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group mb-2">
                            {{ form.old_password.errors }}
                            <label class="text-primary" for="id_old_password"> {% trans 'Current password:' %} </label>
                            <input type="password" class="form-control" id="id_old_password" name="old_password" required>
                        </div>
                        <div class="form-group mb-2">
                            {{ form.new_password1.errors }}
                            <label class="text-primary" for="id_new_password1"> {% trans 'New password:' %} </label>
                            <input type="password" class="form-control" id="id_new_password1" name="new_password1" required>
                            {% if form.new_password1.help_text %}
                                <div class="help">{{ form.new_password1.help_text|safe }}</div>
                            {% endif %}
                        </div>
                        <div class="form-group mb-2">
                            {{ form.new_password2.errors }}
                            <label class="text-primary" for="id_new_password2"> {% trans 'Confirm the new password:' %} </label>
                            <input type="password" class="form-control" id="id_new_password2" name="new_password2" required>
                        </div>
                        <div class="submit-row">
                            <input type="submit" value="{% trans 'Change my password' %}" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
        </div>
</div>
    
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n static %}
{% block custom_css %}
    <link rel="stylesheet" href= "{% static 'accounts/css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'accounts/css/accounts_reset_password_complete.css' %}">
{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <header>
        <a href="{% url 'profile:partner_list' %}" class="logo">
            <img src="{% static 'home/assets/logos/logo-large.png' %}"
                 alt="aproxymeaty logo" >
        </a>
    </header>
    <div class="container d-flex flex-column align-items-center">
            <img class="mb-5" src="{% static 'accounts/imgs/lock-icon.png' %}">    
            <p class="mb-5">
                    {% trans "The password has changed successfully :-)"  %}
            </p> 
            <a class="btn btn-primary" href="{% url 'profile:login' %}" >
                {% trans "Back to the login page"  %}
            </a>
    </div>


{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href= "{% static 'accounts/css/accounts_reset_password.css' %}" >
{% endblock %}
{% block content %}
    <header>
        <a href="{% url 'profile:partner_list' %}" class="logo">
            <img src="{% static 'home/assets/logos/logo-large.png' %}"
                 alt="aproxymeaty logo" >
        </a>
    </header>
    {% if validlink %}

        <div class="container center-container">
                <p>{% trans 'Please enter your new password twice so we can verify you typed it in correctly' %}</p>

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group mb-2">
                        {{ form.new_password1.errors }}
                        <label class="text-primary" for="id_new_password1"> {% trans 'New password:' %} </label>
                        <input type="password" class="form-control" id="id_new_password1" name="new_password1" required>
                    </div>
                    <div class="form-group mb-2">
                            {{ form.new_password2.errors }}
                            <label class="text-primary" for="id_new_password2"> {% trans "Confirm password:" %} </label>
                            <input type="password" class="form-control" id="id_new_password2" name="new_password2" required>
                        </div>            
                        <input class="btn btn-primary" type="submit" value="{% trans 'Change my password' %}" />
                </form>
        </div>

    {% else %}

        <div class="container">
            <p>
                {% trans 'The password reset link was invalid, possibly because it has already been used. Please request a new password reset.' %}
            </p>
            
        </div>
    {% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{{ title }}{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href= "{% static 'accounts/css/style.css' %}" >
    <link rel="stylesheet" href= "{% static 'accounts/css/accounts_reset_password_done.css' %}" >
{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
    <header>
        <a href="{% url 'profile:partner_list' %}" class="logo">
            <img src="{% static 'home/assets/logos/logo-large.png' %}"
                 alt="aproxymeaty logo" >
        </a>
    </header>

    <div class="container">
        <p>
            {% trans "We've emailed you instructions for setting your password, "%}
            {% trans "if an account exists with the email you entered. You should receive them shortly."%}
        </p>
        <p>
            {% trans "If you don't receive an email, please make sure you've entered "%}
            {% trans "the address you registered with, and check your spam folder."%}
        </p>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% extends 'base.html' %}
{% load i18n static %}
{% autoescape off %} 
{% block custom_css %}
    <style type="text/css" rel="stylesheet" media="all">
      /* Base ------------------------------ */
    
      *:not(br):not(tr):not(html) {
        font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;
        box-sizing: border-box;
      }
      
      body {
        width: 100% !important;
        height: 100%;
        margin: 0;
        line-height: 1.4;
        background-color: #F2F4F6;
        color: #74787E;
        -webkit-text-size-adjust: none;
      }
      a.white{
        color: #ffffff;
      }
      p,
      ul,
      ol,
      blockquote {
        line-height: 1.4;
        text-align: left;
      }
      
      a {
        color: #3869D4;
      }
      
      a img {
        border: none;
      }

      /* Layout ------------------------------ */
      .email-wrapper {
        width: 100%;
        margin: 0;
        padding: 0;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
        background-color: #F2F4F6;
      }
      
      .email-content {
        width: 100%;
        margin: 0;
        padding: 0;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
      }
      /* Masthead ----------------------- */
      
      .email-masthead {
        padding: 25px 0;
        text-align: center;
      }
      
      .email-masthead_logo {
        width: 94px;
      }
      
      .email-masthead_name {
        font-size: 16px;
        font-weight: bold;
        color: #bbbfc3;
        text-decoration: none;
        text-shadow: 0 1px 0 white;
      }
      /* Body ------------------------------ */
      
      .email-body {
        width: 100%;
        margin: 0;
        padding: 0;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
        border-top: 1px solid #EDEFF2;
        border-bottom: 1px solid #EDEFF2;
        background-color: #FFFFFF;
      }
      
      .email-body_inner {
        width: 570px;
        margin: 0 auto;
        padding: 0;
        -premailer-width: 570px;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
        background-color: #FFFFFF;
      }
      
      .email-footer {
        width: 570px;
        margin: 0 auto;
        padding: 0;
        -premailer-width: 570px;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
        text-align: center;
      }
      
      .email-footer p {
        color: #AEAEAE;
      }
      
      .body-action {
        width: 100%;
        margin: 30px auto;
        padding: 0;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
        text-align: center;
      }
      
      .body-sub {
        margin-top: 25px;
        padding-top: 25px;
        border-top: 1px solid #EDEFF2;
      }
      
      .content-cell {
        padding: 35px;
      }
      
      .preheader {
        display: none !important;
      }
      /* Attribute list ------------------------------ */
      
      .attributes {
        margin: 0 0 21px;
      }
      
      .attributes_content {
        background-color: #EDEFF2;
        padding: 16px;
      }
      
      .attributes_item {
        padding: 0;
      }
      /* Related Items ------------------------------ */
      
      .related {
        width: 100%;
        margin: 0;
        padding: 25px 0 0 0;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
      }
      
      .related_item {
        padding: 10px 0;
        color: #74787E;
        font-size: 15px;
        line-height: 18px;
      }
      
      .related_item-title {
        display: block;
        margin: .5em 0 0;
      }
      
      .related_item-thumb {
        display: block;
        padding-bottom: 10px;
      }
      
      .related_heading {
        border-top: 1px solid #EDEFF2;
        text-align: center;
        padding: 25px 0 10px;
      }
      /* Discount Code ------------------------------ */
      
      .discount {
        width: 100%;
        margin: 0;
        padding: 24px;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
        background-color: #EDEFF2;
        border: 2px dashed #9BA2AB;
      }
      
      .discount_heading {
        text-align: center;
      }
      
      .discount_body {
        text-align: center;
        font-size: 15px;
      }
      /* Social Icons ------------------------------ */
      
      .social {
        width: auto;
      }
      
      .social td {
        padding: 0;
        width: auto;
      }
      
      .social_icon {
        height: 20px;
        margin: 0 8px 10px 8px;
        padding: 0;
      }
      /* Data table ------------------------------ */
      
      .purchase {
        width: 100%;
        margin: 0;
        padding: 35px 0;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
      }
      
      .purchase_content {
        width: 100%;
        margin: 0;
        padding: 25px 0 0 0;
        -premailer-width: 100%;
        -premailer-cellpadding: 0;
        -premailer-cellspacing: 0;
      }
      
      .purchase_item {
        padding: 10px 0;
        color: #74787E;
        font-size: 15px;
        line-height: 18px;
      }
      
      .purchase_heading {
        padding-bottom: 8px;
        border-bottom: 1px solid #EDEFF2;
      }
      
      .purchase_heading p {
        margin: 0;
        color: #9BA2AB;
        font-size: 12px;
      }
      
      .purchase_footer {
        padding-top: 15px;
        border-top: 1px solid #EDEFF2;
      }
      
      .purchase_total {
        margin: 0;
        text-align: right;
        font-weight: bold;
        color: #2F3133;
      }
      
      .purchase_total--label {
        padding: 0 15px 0 0;
      }
      /* Utilities ------------------------------ */
      
      .align-right {
        text-align: right;
      }
      
      .align-left {
        text-align: left;
      }
      
      .align-center {
        text-align: center;
      }
      /*Media Queries ------------------------------ */
      
      @media only screen and (max-width: 600px) {
        .email-body_inner,
        .email-footer {
          width: 100% !important;
        }
      }
      
      @media only screen and (max-width: 500px) {
        .button {
          width: 100% !important;
        }
      }
      /* Buttons ------------------------------ */
      
      .button {
        background-color: #3869D4;
        border-top: 10px solid #3869D4;
        border-right: 18px solid #3869D4;
        border-bottom: 10px solid #3869D4;
        border-left: 18px solid #3869D4;
        display: inline-block;
        color: #FFF;
        text-decoration: none;
        border-radius: 3px;
        box-shadow: 0 2px 3px rgba(0, 0, 0, 0.16);
        -webkit-text-size-adjust: none;
      }
      
      .button--green {
        background-color: #2E517A;
        border-top: 10px solid #2E517A;
        border-right: 18px solid #2E517A;
        border-bottom: 10px solid #2E517A;
        border-left: 18px solid #2E517A;
      }
      
      .button--red {
        background-color: #FF6136;
        border-top: 10px solid #FF6136;
        border-right: 18px solid #FF6136;
        border-bottom: 10px solid #FF6136;
        border-left: 18px solid #FF6136;
      }
      /* Type ------------------------------ */
      
      h1 {
        margin-top: 0;
        color: #2F3133;
        font-size: 19px;
        font-weight: bold;
        text-align: left;
      }
      
      h2 {
        margin-top: 0;
        color: #2F3133;
        font-size: 16px;
        font-weight: bold;
        text-align: left;
      }
      
      h3 {
        margin-top: 0;
        color: #2F3133;
        font-size: 14px;
        font-weight: bold;
        text-align: left;
      }
      
      p {
        margin-top: 0;
        color: #74787E;
        font-size: 16px;
        line-height: 1.5em;
        text-align: left;
      }
      
      p.sub {
        font-size: 12px;
      }
      
      p.center {
        text-align: center;
      }
    </style>
{% endblock %}

{% block content %}
    <span class="preheader"> {% trans "Use this link to reset your password. The link is only valid for 24 hours." %} </span>
    <table class="email-wrapper" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center">
          <table class="email-content" width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td class="email-masthead">
                <a href="{{ protocol }}://{{ domain }}" class="email-masthead_name">
                  Aproxymeaty
                </a>
              </td>
            </tr>
            <!-- Email Body -->
            <tr>
              <td class="email-body" width="100%" cellpadding="0" cellspacing="0">
                <table class="email-body_inner" align="center" width="570" cellpadding="0" cellspacing="0">
                  <!-- Body content -->
                  <tr>
                    <td class="content-cell">
                      <h1>{% trans "Hi" %} {{name}},</h1>
                      <p> {% trans "You recently requested to reset your password for your Aproxymeaty account. Use the button below to reset it." %} 
                        <strong> {% trans "This password reset is only valid for the next 24 hours." %} </strong>
                      </p>
                      <!-- Action -->
                      <table class="body-action" align="center" width="100%" cellpadding="0" cellspacing="0">
                        <tr>
                          <td align="center">
                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                              <tr>
                                <td align="center">
                                  <table border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                      <td>
                                        <a href="{{ protocol }}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}" class="button button--green white" target="_blank"> {% trans "Reset your password" %} </a>
                                      </td>
                                    </tr>
                                  </table>
                                </td>
                              </tr>
                            </table>
                          </td>
                        </tr>
                      </table>
                      <p>{% trans "If you did not request a password reset, please ignore this email or" %}
                        <a href="#">{% trans "contact support" %}</a> {% trans "if you have questions." %} </p>
                      <p>{% trans "Thanks," %}
                        <br> {% trans "The Aproxymeaty Team" %} </p>
                      <!-- Sub copy -->
                      <table class="body-sub">
                        <tr>
                          <td>
                            <p class="sub"> {% trans "If you’re having trouble with the button above, copy and paste the URL below into your web browser." %} </p>
                            <p class="sub">{{ protocol }}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}</p>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td>
                <table class="email-footer" align="center" width="570" cellpadding="0" cellspacing="0">
                  <tr>
                    <td class="content-cell" align="center">
                      <p class="sub align-center">&copy; 2018 Aproxymeaty. All rights reserved.</p>
                      <p class="sub align-center">
                        <br>1234 Street Rd.
                        <br>Suite 1234
                      </p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
{% endblock %}
{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{{ title }}{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href= "{% static 'accounts/css/accounts_reset_password.css' %}" >
{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
    <header>
        <a href="{% url 'profile:partner_list' %}" class="logo">
            <img src="{% static 'home/assets/logos/logo-large.png' %}"
                 alt="aproxymeaty logo" >
        </a>
    </header>

    <div class="container reset-password-body">
        <h3>{% trans "Did you forget your password?" %}</h3>
        <p>
            {% trans "Enter your email address below, and we'll email instructions for setting a new one." %}
        </p>
    
        <form method="post">
            {% csrf_token %}
                <div class="form-group mb-2">
                    {{ form.email.errors }}
                    <label class="text-primary" for="id_email"> {% trans 'Email address:' %} </label>
                    <input type="email" class="form-control" id="id_email" name="email" required>
                </div>
                <button type="submit" class="btn btn-primary"> {% trans "Send verification email" %} </button>
            </form>
        </div>
    </div>

{% endblock %}