aproximeaty/urls.py
# NOTICE OF LICENSE
# This file is licenced under the Software License Agreement.
# With the purchase or the installation of the software in your application
# you accept the licence agreement.
#
# You must not modify, adapt or create derivative works of this source code
#
# @author: EL AKIOUI Zouhaire
# @copyright 2018
# @license   licence.txt


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.conf import settings
from aproximeaty import views as common_view


urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^item/', include('items.urls', namespace='item')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
]

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = common_view.handler404
handler500 = common_view.handler500

dashboard/urls.py
from django.conf.urls import url
from .views import (
    DashboardView
)

urlpatterns = [
    url(r'^', DashboardView.as_view(), name='home'),
]

home/urls.py
from django.conf.urls import url
from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, UpdateView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from checkout.models import OrderDetail, SavingAccount
from .utils import get_partner_dashboard, get_customer_board


class DashboardView(LoginRequiredMixin, View):
    template_name = 'dashboard/partner/partner.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.user.profile == 'partner':
                context = get_partner_dashboard(request)
                return render(request,
                              template_name='dashboard/partner/partner.html',
                              context=context
                              )

            if request.user.profile == 'customer':
                order_details = get_customer_board(request)
                return render(request,
                              template_name='dashboard/customer/customer.html',
                              context={'order_details': order_details})

            return HttpResponseRedirect(reverse_lazy('profile:partner_list'))
        except Exception as e:
            print(e)
            pass

dashboard/templates/dashboard/snippets/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}?version=2" type="text/css">
<link rel="stylesheet" href="{% static 'profiles/css/subscription.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'payment/css/payment.css' %}" type="text/css">

dashboard/templates/dashboard/snippets/js.html
{% load static  %}
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="https://js.stripe.com/v2/"></script>
<script src="{% static 'dashboard/js/dashboard.js'%}"></script>

dashboard/templates/dashboard/snippets/sidebar-menu.html
{% load static %}
{% load i18n %}
<nav id="sidebar">
    <div class="sidebar-header">
        <a href="{% url 'profile:partner_list' %}">
            <img src="{% static 'dashboard/logos/aproxymeaty-logo.png' %}" alt="aproxymeaty log">
        </a>

    </div>

    <ul class="list-unstyled components">
            <li class="">
                    <a href="{% url 'dashboard:home' %}">
                            {% trans 'Home' %}
                    </a>
                </li>
                
                {% if request.user.profile == 'partner'%}
                   <li>
                       <a href="{% url 'profile:edit-partner' request.user.slug %}">
                            {% trans 'Edit profile' %}
                       </a>
                   </li>
                   <li>
                       <a href="{% url 'profile:detail-partner' request.user.slug %}">
                            {% trans 'Display profile' %}
                       </a>
                   </li>
                    <li>
                        <a href="{% url 'payment:partner-show-bank-account' %}">
                            {% trans 'Payment Methods' %}
                        </a>
                    </li>

                {% else %}
                    <li>
                        <a href="{% url 'profile:edit-customer' request.user.slug %}">
                            {% trans 'Edit profile' %}
                        </a>
                    </li>
                     <li>
                        <a href="{% url 'payment:customer-show-card' %}">
                            {% trans 'Payment Methods' %}
                        </a>
                    </li>

        
                {% endif %}

                <li>
                    <a href="{% url 'account:password_change' %}">
                        {% trans 'Change password' %}
                    </a>
                </li>
                
    </ul>
</nav>

dashboard/templates/dashboard/snippets/top-menu.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fas fa-align-left"></i>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item mr-3" id="go-to-website">
                        <a href="{% url 'profile:partner_list' %}">
                            <i class="fa fa-globe"></i>
                            {% trans 'Go to Website' %}
                        </a>
                </li>
                <li class="nav-item">
                        <a href="{% url 'account:logout'  %}">
                            <i class="fas fa-sign-out-alt"></i>
                            {% trans 'LogOut' %}
                        </a>
                </li>
            </ul>
        </div>
    </div>
</nav>