aproximeaty/urls.py
# NOTICE OF LICENSE
# This file is licenced under the Software License Agreement.
# With the purchase or the installation of the software in your application
# you accept the licence agreement.
#
# You must not modify, adapt or create derivative works of this source code
#
# @author: EL AKIOUI Zouhaire
# @copyright 2018
# @license   licence.txt


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.conf import settings
from aproximeaty import views as common_view


urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^item/', include('items.urls', namespace='item')),
    url(r'^checkout/', include('checkout.urls', namespace='checkout')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
]

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = common_view.handler404
handler500 = common_view.handler500

home/urls.py
from django.conf.urls import url
from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
]

payment/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import (
    CustomerAddCardView,
    CustomerShowCardView,
    CustomerDefaultCardView,
    CustomerDeleteCardView,
    PartnerAddBankAccountView,
    PartnerShowBankAccountView,
    PartnerDeleteBankAccountView,
    PartnerDefaultBankView
)


urlpatterns = [
    url(r'^customer/$', CustomerShowCardView.as_view(), name='customer-show-card'),
    url(r'^customer/add$', CustomerAddCardView.as_view(), name='customer-add-card'),
    url(r'^customer/set/default/(?P<card_id>[\w-]+)$',
        CustomerDefaultCardView.as_view(),
        name='customer-default-card'),
    url(r'^customer/delete/(?P<card_id>[\w-]+)$',
        CustomerDeleteCardView.as_view(),
        name='customer-delete-card'),
    url(r'^partner/$', PartnerShowBankAccountView.as_view(), name='partner-show-bank-account'),
    url(r'^partner/add$', PartnerAddBankAccountView.as_view(), name='partner-add-bank-account'),
    url(r'^partner/delete/(?P<bank_id>[\w-]+)$',
        PartnerDeleteBankAccountView.as_view(),
        name='partner-delete-bank-account'),
    url(r'^partner/set/default/(?P<bank_id>[\w-]+)$',
        PartnerDefaultBankView.as_view(),
        name='partner-default-bank'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from .utils import (
    add_external_account,
    create_stripe_customer_account,
    get_stripe_customer_acct,
    customer_default_card,
    add_card_to_customer,
    delete_card_to_customer,
    create_connected_account,
    get_stripe_partner_acct,
    delete_bank_account_to_partner,
    partner_default_bank
)
from profiles.models import Customer, Partner


class CustomerDeleteCardView(View):
    template_name = 'payment/customer_show_card.html'

    def get(self, request, *args, **kwargs):
        try:
            customer = Customer.objects.get(id=request.user.id)
            delete_card_to_customer(customer, kwargs.get('card_id'))
            return JsonResponse({'message': 'success'}, status=200)
        except Exception as e:
            return JsonResponse({'error': e}, status=500)


class CustomerDefaultCardView(View):
    template_name = 'payment/customer_show_card.html'

    def get(self, request, *args, **kwargs):
        try:
            customer = Customer.objects.get(id=request.user.id)
            customer_default_card(customer, kwargs.get('card_id'))

            return HttpResponseRedirect(reverse_lazy('payment:customer-show-card'))
        except Exception as e:
            stripe_customer_acct = get_stripe_customer_acct(customer)
            return render(
                request,
                template_name=self.template_name,
                context={'error': e, 'stripe_customer_acct': stripe_customer_acct}
            )


class CustomerShowCardView(View):
    template_name = 'payment/customer_show_card.html'

    def get(self, request):
        try:
            customer = Customer.objects.get(id=request.user.id)
            stripe_customer_acct = get_stripe_customer_acct(customer)
            return render(request,
                          template_name=self.template_name,
                          context={'stripe_customer_acct':stripe_customer_acct}
                          )
        except Exception as e:

            return render(
                request,
                template_name=self.template_name,
                context={'error': e}
            )


class CustomerAddCardView(View):
    template_name = 'payment/customer_add_card.html'

    def get(self, request):
        print('CustomerAddCardView GET')

        return render(
            request,
            template_name=self.template_name,
            context={}
        )

    def post(self, request):
        try:
            card_id = request.POST.get('stripeToken')
            customer = Customer.objects.get(id=request.user.id)
            if customer.payment_id is None:
                create_stripe_customer_account(customer, card_id)
            else:
                add_card_to_customer(customer, card_id)

            return HttpResponseRedirect(reverse_lazy('payment:customer-show-card'))
        except Exception as e:
            return render(
                request,
                template_name=self.template_name,
                context={'error': e}
            )


class PartnerShowBankAccountView(View):
    template_name = 'payment/partner_show_bank_account.html'

    def get(self, request):
        try:
            stripe_partner_acct = get_stripe_partner_acct(request.user.id)
            return render(
                request,
                template_name=self.template_name,
                context={'stripe_partner_acct':stripe_partner_acct}
            )
        except Exception as e:
            return render(
                request,
                template_name=self.template_name,
                context={'error': e}
            )


class PartnerAddBankAccountView(View):
    template_name = 'payment/partner_add_bank_account.html'

    def get(self, request):

        return render(
            request,
            template_name=self.template_name,
            context={'error': ''}
        )

    def post(self, request):
        try:
            bank_id = request.POST.get('stripeToken')
            partner = Partner.objects.get(id=request.user.id)
            if not partner.payment_id:
                create_connected_account(partner, bank_id)
            else:
                add_external_account(partner, bank_id)
            return HttpResponseRedirect(reverse_lazy('payment:partner-show-bank-account'))
        except Exception as e:

            return render(
                request,
                template_name=self.template_name,
                context={'error': e}
            )


class PartnerDeleteBankAccountView(View):
    template_name = 'payment/partner_show_bank_account.html'

    def get(self, request, *args, **kwargs):
        try:
            partner = Partner.objects.get(id=request.user.id)
            delete_bank_account_to_partner(partner, kwargs.get('bank_id'))
            return JsonResponse({'message': 'success'}, status=200)
        except Exception as e:
            return JsonResponse({'error': e}, status=500)


class PartnerDefaultBankView(View):
    template_name = 'payment/partner_show_bank_account.html'

    def get(self, request, *args, **kwargs):
        try:

            partner = Partner.objects.get(id=request.user.id)
            partner_default_bank(partner, kwargs.get('bank_id'))
            return HttpResponseRedirect(reverse_lazy('payment:partner-show-bank-account'))

        except Exception as e:
            print(e)
            stripe_partner_acct = get_stripe_partner_acct(request.user.id)
            return render(
                request,
                template_name=self.template_name,
                context={'error': e, 'stripe_partner_acct': stripe_partner_acct}
            )

payment/templates/payment/bank_confirm_delete.html
{% load i18n %}
<div class="modal fade" id="confirm-delete-bank"
     tabindex="-1"
     role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                {% trans 'Delete Bank'%}
            </div>
            <div class="modal-body">
                {% trans 'Are you sure you want to delete this bank ?'%}
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn btn-default"
                        data-dismiss="modal">
                    {% trans 'Cancel'%}
                </button>
                <a class="btn btn-danger "
                   id="btn-ok" href="">
                    {% trans 'Delete'%}
                </a>
            </div>
        </div>
    </div>
</div>

payment/templates/payment/card_confirm_delete.html
{% load i18n %}
<div class="modal fade" id="confirm-delete-card"
     tabindex="-1"
     role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                {% trans 'Delete Card'%}
            </div>
            <div class="modal-body">
                {% trans 'Are you sure you want to delete this card ?'%}
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn btn-default"
                        data-dismiss="modal">
                    {% trans 'Cancel'%}
                </button>
                <a class="btn btn-danger "
                   id="btn-card-ok" href="">

                    {% trans 'Delete'%}
                </a>
            </div>
        </div>
    </div>
</div>

payment/templates/payment/customer_add_card.html
{% extends 'dash-base.html' %}
{% load static %}
{% load i18n %}
{% block head_title %}
{% trans 'Add Payment Method' %}
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/payments-methodes.css' %}" type="text/css">
{% endblock %}
{% block content%}
    <div class="wrapper">
        <!-- Sidebar -->
        {% include 'dashboard/snippets/sidebar-menu.html' %}
        <!-- Page Content -->
        <div id="content">
            <!-- Top menu -->
            {% include 'dashboard/snippets/top-menu.html' %}
            <!-- Payments Methods page -->
            <div class="container-fluid">
              <div class="row">
                <div class="bg-white col col-md-6 offset-md-3 pt-5 pb-5">
                  <h4 class="text-center">
                    {% trans 'Add New Payment Method' %}
                  </h4>
                  <div class="divider mb-3"></div>
                    <form action="{% url 'payment:customer-add-card' %}"
                          method="post"
                          id="customer-credit-card-form"
                          class=" px-md-5 py-md-3"
                    >
                        {% csrf_token %}

                        <div class="card-errors"></div>
                        <div class="row">
                            <div class="form-group col-xs-12 col-md-8">
                                <small id="card-number-help" class="form-text text-primary">
                                    {% trans 'Card number' %}
                                </small>
                                <input type="text"
                                       class="form-control card-number"
                                       id="card-number"
                                       aria-describedby="card-number"
                                       placeholder="{% trans 'Card number' %}">

                            </div>
                            <div class="form-group col-xs-12 col-md-4">
                                <small id="cvc-help" class="form-text text-primary">
                                    {% trans 'cvc' %}
                                </small>
                                <input type="text"
                                       class="form-control cvc"
                                       id="cvc"
                                       aria-describedby="cvc"
                                       placeholder="{% trans 'cvc' %}">
                            </div>
                        </div>
                        <h6 class="text-primary text-uppercase">{% trans 'Expire date' %}</h6>
                        <div class="row">
                            <div class="form-group col-6 col-md-4 offset-md-2">
                                <small id="card-expiry-month-help" class="form-text text-muted">
                                    {% trans 'Month' %}
                                </small>
                                <input type="text"
                                        class="form-control card-expiry-month"
                                        id="card-expiry-month"
                                        aria-describedby="card-expiry-month"
                                        placeholder="{% trans 'Month' %}">
                            </div>
                            <div class="form-group col-6 col-md-4">
                                <small id="card expiry year help" class="form-text text-muted">
                                    {% trans 'Year' %}
                                </small>
                                <input type="text"
                                        class="form-control card-expiry-year"
                                        id="card-expiry-year"
                                        aria-describedby="card-expiry-year"
                                        placeholder="{% trans 'Year' %}">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-block btn-primary mt-5" > {% trans 'Submit' %}</button>
                    </form>
                </div>
              </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block custom-js %}
      <script src="{% static 'payment/js/credit-card.js' %}" ></script>
{% endblock custom-js %}

payment/templates/payment/customer_show_card.html
{% extends 'dash-base.html' %}
{% load static %}
{% load i18n %}
{% block head_title %}
{% trans 'Payments Methods' %}
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/payments-methodes.css' %}" type="text/css">
{% endblock %}
{% block content%}
    <div class="wrapper">
        <!-- Sidebar -->
        {% include 'dashboard/snippets/sidebar-menu.html' %}
        <!-- Page Content -->
        <div id="content">
            <!-- Top menu -->
            {% include 'dashboard/snippets/top-menu.html' %}
            <!-- Payments Methods page -->
            <div class="container-fluid">
                     <div class="bank-errors">
                         {% if error %}
                            {{error}}
                         {% endif %}
                     </div>
                    <div class="row">
                        {% for card in stripe_customer_acct.sources.data %}
                            <div class="col col-md-4 p-3">
                                <div class="bg-white payment-methode-card p-3 d-flex flex-column justify-content-between">
                                    <div class="">
                                        <div class="payment-type text-uppercase">
                                            {{card.brand}}
                                        </div>
                                        <div class="payment-account text-uppercase">
                                            xxxxxxxxxxxx{{ card.last4}}
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row justify-content-between">
                                        <div>
                                            {% if card.id == stripe_customer_acct.default_source %}
                                               {% trans 'Default' %}
                                            {% else %}
                                                 <a class="btn btn-link"
                                                   href="{% url 'payment:customer-default-card' card.id %}">
                                                    {% trans 'Set Default' %}
                                                </a>
                                            {% endif %}

                                          <button id="{{card.id}}"
                                                  type="button"
                                                  class="btn btn-danger delete-card">
                                              <i class="fas fa-trash-alt"></i>
                                          </button>
                                        </div>
                                        <img src="{% static 'payment/img/'|add:card.brand|add:'.png' %}" height="35px">
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col col-md-4 p-3">
                            <a class="btn bg-white payment-methode-card d-flex flex-column justify-content-center align-items-center"
                                href="{% url 'payment:customer-add-card' %}">
                                <img src="{% static 'checkout/img/plus-icon.png' %}" height="64px">
                                <div class="mt-3">
                                    {% trans 'Add Payment Method' %}
                                </div>
                            </a>
                        </div>
                    </div>

            </div>

        </div>
    </div>
     {% include 'payment/card_confirm_delete.html'%}
{% endblock content %}
{% block custom-js %}
    {% include 'payment/snippets/js.html'%}
{% endblock custom-js %}

payment/templates/payment/partner_add_bank_account.html
{% extends 'dash-base.html' %}
{% load static %}
{% load i18n %}
{% block head_title %}
    {% trans 'Add Payment Method' %}
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/payments-methodes.css' %}" type="text/css">
{% endblock %}
{% block content%}
    <div class="wrapper">
        <!-- Sidebar -->
        {% include 'dashboard/snippets/sidebar-menu.html' %}
        <!-- Page Content -->
        <div id="content">
            <!-- Top menu -->
            {% include 'dashboard/snippets/top-menu.html' %}
            <!-- Payments Methods page -->
            <div class="container-fluid">
              <div class="row bg-white">
                <div class="col col-md-8 offset-md-2 pt-5 pb-5">
                  <h4 class="text-center">
                    {% trans 'Add New Payment Method (Bank)' %}
                  </h4>
                  <div class="divider mb-3"></div>
                    <form action="{% url 'payment:partner-add-bank-account' %}"
                          method="post"
                          id="partner-bank-account-form"
                    >
                        {% csrf_token %}
                         <div class="bank-errors"></div>
                         <div class="row">
                            <div class="form-group col-6">
                                <label>
                                    {% trans 'Country' %}
                                </label>
                                <input type="text"
                                        class="form-control country"
                                        id="country"
                                        aria-describedby="country"
                                        placeholder="{% trans 'Country' %}">
                                <small id="country-help" class="form-text text-muted">
                                    {% trans 'Ex: fr for France, de for Germany, ...' %}
                                </small>
                            </div>
                            <div class="form-group col-6">
                                <label for="currency">
                                    {% trans 'Currency' %}
                                </label>
                                <input type="text"
                                        class="form-control currency"
                                        id="currency"
                                        aria-describedby="currency"
                                        placeholder="{% trans 'Currency' %}">
                                <small id="currency-help" class="form-text text-muted">
                                    {% trans 'Ex. usd, eur...' %}
                                </small>
                            </div>
                         </div>
                        <div class="form-group">
                            <label for="routing-number">
                                {% trans 'Routing number' %}
                            </label>
                            <input type="text"
                                   class="form-control routing-number"
                                   id="routing-number"
                                   aria-describedby="routing-number"
                                   placeholder="{% trans 'Routing number' %}">
                            <small id="routing-number-help" class="form-text text-muted">
                                {% trans 'For non IBAN accounts only' %}
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="account-number">
                                {% trans 'Account number' %}
                            </label>
                            <input type="text"
                                   class="form-control account-number"
                                   id="account-number"
                                   aria-describedby="account-number"
                                   placeholder="{% trans 'Account number' %}">
                            <small id="account-number-help" class="form-text text-muted">
                                {% trans 'For EU contries use IBAN' %}
                            </small>
                        </div>
                        <div class="row">
                            <div class="form-group col-12 col-md-8">
                                <label for="account-holder-name">
                                    {% trans "Account holder's name" %}
                                </label>
                                <input type="text"
                                        class="form-control account-holder-name"
                                        id="account-holder-name"
                                        aria-describedby="account holder's name"
                                        placeholder="{% trans 'Account holder\'s name' %}">
                                <small id="account-holder-name-help" class="form-text text-muted">

                                </small>
                            </div>
                            <div class="form-group col-12 col-md-4">
                                <label for="account-holder-type">
                                    {% trans "Account holder's type" %}
                                </label>
                                <input type="text"
                                        class="form-control account-holder-type"
                                        id="account-holder-type"
                                        aria-describedby="account holder's type"
                                        placeholder="{% trans 'Company or individual' %}">
                                <small id="account-holder-type-help" class="form-text text-muted">

                                </small>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block mt-3" > Submit</button>
                    </form>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block custom-js %}
  <script src="{% static 'payment/js/bank-account.js' %}" ></script>
{% endblock custom-js %}

payment/templates/payment/partner_show_bank_account.html
{% extends 'dash-base.html' %}
{% load static %}
{% load i18n %}
{% block head_title %}
{% trans 'Payments Methods' %}
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/payments-methodes.css' %}" type="text/css">
{% endblock %}
{% block content%}
    <div class="wrapper">
        <!-- Sidebar -->
        {% include 'dashboard/snippets/sidebar-menu.html' %}
        <!-- Page Content -->
        <div id="content">
            <!-- Top menu -->
            {% include 'dashboard/snippets/top-menu.html' %}
            <!-- Payments Methods page -->
            <div class="container-fluid">
                     <div class="bank-errors">
                         {% if error %}
                            {{error}}
                         {% endif %}

                     </div>
                    <div class="row">
                        {% for bank in stripe_partner_acct.external_accounts.data %}
                            <div class="col col-md-4 p-3">
                                <div class="bg-white payment-methode-card p-3 d-flex flex-column justify-content-between">
                                    <div class="">
                                        <div class="payment-type text-uppercase">
                                            {{bank.bank_name}}
                                        </div>
                                        <div class="payment-account text-uppercase">
                                            xxxxxxxxxxxx{{ bank.last4}}
                                        </div>
                                    </div>
                                    {% if bank.default_for_currency == False %}
                                        <div class="d-flex flex-row justify-content-between">
                                            <div>
                                                 <a class="btn btn-link"
                                                   href="{% url 'payment:partner-default-bank' bank.id %}">
                                                    {% trans 'Set Default for : ' %} {{bank.currency}}
                                                </a>
                                                <button id="{{bank.id}}"
                                                        type="button"
                                                        class="btn btn-danger delete-bank">
                                                    <i class="fas fa-trash-alt"></i>
                                                </button>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col col-md-4 p-3">
                            <a class="btn bg-white payment-methode-card d-flex flex-column justify-content-center align-items-center"
                                href="{% url 'payment:partner-add-bank-account' %}">
                                <img src="{% static 'checkout/img/plus-icon.png' %}" height="64px">
                                <div class="mt-3">
                                    {% trans 'Add Payment Method' %}
                                </div>
                            </a>
                        </div>
                    </div>

            </div>

        </div>
    </div>
    {% include 'payment/bank_confirm_delete.html'%}
{% endblock content %}
{% block custom-js %}
    {% include 'payment/snippets/js.html'%}
{% endblock custom-js %}